### ISSUE TITLE
Bridge log is incomplete - missing trawls

### ISSUE THREAD

**Issue by jclgan** [HakaiInstitute/iys-oos#20]
Only have records for 49 trawls; however, there were 60 stations total according to Chlorophyll, POM, Nutrients, CTD, and Plastics datasets. 

Bridge log data is in Trawl dataset file `JuvSalmon_2019-01_catch.v19.02a.xlsx`

**Comment by Br-Johnson** [comment]
This should be solved when we receive the new bridge log from Alexei and Chrys.

**Comment by Br-Johnson** [comment]
@jclgan Is this solved by the receipt if the new bridge log? Or is there an outstanding question here?

**Comment by jclgan** [comment]
> @jclgan Is this solved by the receipt if the new bridge log? Or is there an outstanding question here?

I'll have to cross-reference the trawl log against the CTD/niskin cast stations to verify

**Comment by Br-Johnson** [comment]
Though we recieved a new bridge log from Aleksey. Chrys Neville mentioned that she still wanted to review and finalize with Chrys over the coming weeks. So, we should standby on publishing the actual data we have thus far.

**Comment by jclgan** [comment]
I don't think the trawl dataset can be appropriately used as a bridge log because it's still missing a lot of information. 

Like the 'BRIDGE_LOG_FINAL' sheet in the trawl file JuvSalmon_2019-01_catch.v19.02a.xlsx contains all of the navigational logs, comments etc. 

The 2019_GoA_Fish_data_Hakai.xlsx file is just species occurrence data.

**Comment by Br-Johnson** [comment]
OK, so it seems there is a separate bridge log and Trawl log?

**Comment by timvdstap** [comment]
Chatted with Chrys tonight, she told me that Svetlana is currently resolving the final (bi)catch data, and we should receive it early next week. Finalized data should come in two files: catch file (contains bridgelog + total catch) and specimen file (= individual fish data). There will also be a README file and DNA data (colour-coded to indicated which data is preliminary). For the DNA data we will need to tidy both the 'assigned' data and raw data. She will also send me photocopies of raw trawl data sheets/raw catch logs, which will be good to have as back-up.

She will also send me hydro-acoustic data, and metadata (lat/longs) for the Bongo dataset and a surface water sample set (I can't remember the name - something like Newston?). Alternatively, Brian should have the Bongo (meta)data. 

She recommended that Svetlana Esenkulova (PSF) could help with translating the Juday data that we currently have (but that has Russian headings). For any questions related to Fish Trawl Abundance and the DNA data that we be receiving, she will be a good resource and we should contact her should we have any questions.

**Comment by Br-Johnson** [comment]
Has any of this come through?

**Comment by timvdstap** [comment]
> Has any of this come through?

Unfortunately, no. That being said I haven't asked or pushed Chrys for it, as I wasn't sure where things now stand and whether there have been 'higher-level' conversations. Also, I'm not sure if concerns regarding the security/privacy of the data repositories (GoogleDrive/GitHub) have been sufficiently addressed -- I think it would be good to try and push the DMAC along, and see if that resolves any hesitations that scientists/data providers might have?

**Comment by Br-Johnson** [comment]
Ok. That's what I assumed, just checkin. It's not really Chrys's fault, she wants to provide the data but her hands may be tied.
